name: cicd pipeline for terraform ans ansible
on:
    push:
        branches:
            - main
jobs:
    ansible:
        name: ansible deployments
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: install ansible
              run: sudo apt update && sudo apt install ansible -y

            - name: install ansible galaxy roles
              run: ansible-galaxy install -r ./ansible/requirements.yml

            - name: install prom
              run: ansible-playbook -i ./ansible/hosts ./ansible/promethus.yml

            - name: install grafana
              run: ansible-playbook -i ./ansible/hosts ./ansible/grafana.yml