name: cicd pipeline for terraform ans ansible
on:
    push:
        branches:
            - main
jobs:
    ansible:
        name: ansible deployments
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: install ansible
              run: sudo apt update && sudo apt install ansible -y


            - name: Install Ansible Collection [Prometheus]
              run: ansible-galaxy collection install prometheus.prometheus

            - name: Install Ansible Collection [Grafana]
              run: ansible-galaxy collection install grafana.grafana

            - name: install 
              run: ansible-playbook -i ./ansible/hosts requirements.yml